//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiJWT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public short Codigo { get; set; }
        public string Usuario1 { get; set; }
        public string NombreUsuario { get; set; }
        public byte[] Contraseña { get; set; }
    }
}
